---
# tasks file for Fedora

- name: Fedora | Create directory /etc/systemd/resolved.conf.d/
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d/
    state: directory
    mode: '0755'

- name: Fedora | Create /etc/systemd/resolved.conf.d/dns.conf to disable systemd-resolved DNSStubListener
  ansible.builtin.template:
    src: "resolved_dns.conf.j2"
    dest: /etc/systemd/resolved.conf.d/dns.conf
    mode: '0644'
  notify: Restart systemd-resolved
