---
# handlers file for unbound

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Reload NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
